# **Data Analysis with Python**

In [5]:
# List heterogenous
[1,2,3,4, 1.2, 'ybi']

[1, 2, 3, 4, 1.2, 'ybi']

In [2]:
import numpy as np

In [8]:
np.array(['1',2,3,4, 1.2])

array(['1', '2', '3', '4', '1.2'], dtype='<U32')

## Creating Array

In [31]:
arr1 = np.array([
    1,2,3,4,5,6,7,8,9,10
    ])

In [17]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# Shape
arr1.shape

(6,)

In [15]:
arr2.shape

(2, 3)

In [20]:
# Dimension
arr1.ndim

1

In [21]:
arr2.ndim

2

In [22]:
# Size
arr1.size

6

In [23]:
arr2.size

6

## Indexing

In [26]:
arr1[-4]

np.int64(3)

## Slicing

In [27]:
arr1

array([1, 2, 3, 4, 5, 6])

In [29]:
arr1[:3]

array([1, 2, 3])

In [30]:
arr1[ : -3]

array([1, 2, 3])

In [32]:
arr1[-1]

np.int64(10)

In [35]:
arr1[-3:]

array([ 8,  9, 10])

In [45]:
arr2 = np.array([
    [10,-20,-30],
    [40,50,60],
    [70,80,90]
])

In [46]:
arr2[ [2,0,1,2]         ,   [0,2,0,1]         ]

array([ 70, -30,  40,  80])

In [40]:
# first column
arr2[ 0:1 , 0:2]

array([[10, 20]])

In [37]:
# first row
arr2[0]

array([10, 20, 30])