# **Day 2 NumPy Operations**

## **Arithmetic Operations**

In [3]:
2 + 5

7

In [4]:
True + True

2

In [14]:
my_list = [80, 90, 75, 88]

In [16]:
[x + 5 for x in my_list]

[85, 95, 80, 93]

In [17]:
[x + 5 for x in my_list]

TypeError: 'list' object is not callable

In [10]:
my_list.append(5)

In [13]:
my_list

[85, 95, 80, 93, 10]

In [12]:
for i in range(len(my_list)):
    my_list[i] += 5
print(my_list)

[85, 95, 80, 93, 10]


In [6]:
import numpy as np

In [ ]:
my_array = np.array([80, 90, 75, 88])

In [ ]:
my_list +5

TypeError: can only concatenate list (not "int") to list

In [ ]:
my_array

array([80, 90, 75, 88])

In [ ]:
my_array + 5

array([85, 95, 80, 93])

In [ ]:
my_array - 5

array([75, 85, 70, 83])

In [ ]:
my_array * 2

array([160, 180, 150, 176])

In [ ]:
my_array / 2

array([40. , 45. , 37.5, 44. ])

In [ ]:
my_array**2

array([6400, 8100, 5625, 7744])

In [ ]:
my_array**(1/3)

array([4.30886938, 4.48140475, 4.21716333, 4.44796018])

## **Universal Functions (ufunc)**

In [ ]:
arr = np.array([1,4,9,16])

In [ ]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [ ]:
np.square(arr)

array([  1,  16,  81, 256])

In [ ]:
np.abs([-2,-3,-4])

array([2, 3, 4])

In [ ]:
np.round([2.3416, -5.678],2)

array([ 2.34, -5.68])

## **Aggregation Functions**

In [ ]:
marks = np.array([78,85,91,70,88])

In [ ]:
np.sum(marks)

np.int64(412)

In [ ]:
np.mean(marks)

np.float64(82.4)

In [ ]:
np.min(marks)

np.int64(70)

In [ ]:
np.max(marks)

np.int64(91)

## **Reshape**

In [ ]:
arr = np.arange(1,145)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144])

In [ ]:
arr.shape

(12,)

In [ ]:
arr.reshape(1,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144]])

In [ ]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144])

In [ ]:
arr.flatten().shape

(144,)

## **Boolean Masking**

In [ ]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144])

In [ ]:
arr>80

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
arr[100]

np.int64(101)

In [ ]:
arr[arr!=80]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144])

## **Random Generation**

In [ ]:
np.random.rand(5)

array([0.41074848, 0.45839219, 0.5879911 , 0.39913693, 0.09451387])

In [ ]:
np.random.randint(1,200,5)

array([168, 168,  14, 177, 158])

In [ ]:
['ai group', 'ml group', 'python group']

['ai group', 'ml group', 'python group']

In [ ]:
np.random.choice(['ai group', 'ml group', 'python group'],1)

array(['ml group'], dtype='<U12')

In [ ]:
# Exercise 1
sales = np.array ([2500,5000,4300,57000])*1.1

In [ ]:
np.sum(sales)

np.float64(75680.0)

In [ ]:
np.mean(sales)

np.float64(18920.0)

In [ ]:
# 100 student marks
marks = np.random.randint(0,101,100)

# **📑Assignment**
A company recorded the sales of 12 months.

sales = np.array([120,150,170,160,180,200,210,195,205,220,230,250])

Perform the following:

- the total annual sales.
- Find the average monthly sales.
- Find the highest and lowest sales.
- Increase every month's sales by 10%.

- Display only the months where sales exceeded 200.

- Reshape the data into a 3 × 4 matrix.
-Flatten the matrix back into a 1D array.

In [7]:
arr2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [8]:
arr2.shape

(3, 3)

In [11]:
arr2.reshape(1,9)

array([[10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [12]:
arr2.reshape(1,-1)

array([[10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [13]:
arr2.reshape(-1,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

# Broadcasting

In [16]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0

In [17]:
a.shape

(3,)

In [19]:
a*b

array([2., 4., 6.])

In [20]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

In [21]:
a.shape

(4, 3)

In [22]:
b = np.array([1.0, 2.0, 3.0])

In [23]:
b.shape

(3,)

In [24]:
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [25]:
b = np.array([1.0, 2.0, 3.0, 4.0])

In [26]:
b.shape

(4,)

In [29]:
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

# **📑Assignment**
A company recorded the sales of 12 months.

sales = np.array([120,150,170,160,180,200,210,195,205,220,230,250])

Perform the following:

- the total annual sales.
- Find the average monthly sales.
- Find the highest and lowest sales.
- Increase every month's sales by 10%.

- Display only the months where sales exceeded 200.

- Reshape the data into a 3 × 4 matrix.
-Flatten the matrix back into a 1D array.

In [30]:
import numpy as np

In [31]:
sales = np.array([120,150,170,160,180,200,210,195,205,220,230,250])

In [32]:
sales

array([120, 150, 170, 160, 180, 200, 210, 195, 205, 220, 230, 250])

In [33]:
# Total sales
np.sum(sales)

np.int64(2290)

In [34]:
np.mean(sales)

np.float64(190.83333333333334)

In [35]:
np.max(sales)

np.int64(250)

In [36]:
np.min(sales)

np.int64(120)

In [41]:
sales

array([120, 150, 170, 160, 180, 200, 210, 195, 205, 220, 230, 250])

In [37]:
sales>200

array([False, False, False, False, False, False,  True, False,  True,
        True,  True,  True])

In [46]:
sales[5]

np.int64(200)

In [47]:
sales[sales>200]

array([210, 205, 220, 230, 250])

In [48]:
sales * 1

array([120, 150, 170, 160, 180, 200, 210, 195, 205, 220, 230, 250])

In [49]:
sales * 2

array([240, 300, 340, 320, 360, 400, 420, 390, 410, 440, 460, 500])

In [51]:
sales *1.1

array([132. , 165. , 187. , 176. , 198. , 220. , 231. , 214.5, 225.5,
       242. , 253. , 275. ])

In [76]:
np.random.seed(2222222)
np.random.randint(1,10000,5)


array([4011, 9018, 1727, 1863, 9585])

In [ ]:
3776, 5201, 7260, 4024, 1294
236, 5193, 906, 7814, 2896